config/routes.rb
Rails.application.routes.draw do
  resources :games do
    resources :players do
      member do
        post 'draw'
        post 'playmerc', to: 'players#play_merc'
        post 'playpirate', to: 'players#play_pirate'

      end
    end
  end
  get '/sign_in', to: 'sessions#sign_in', as: 'sign_in'
  get '/sign_out', to: 'sessions#sign_out', as: 'sign_out'
  post '/sign_in', to: 'sessions#create'
  delete '/sign_out', to: 'sessions#destroy'

  resources :users

  root 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_one :deck
  has_many :players
  has_one :board


  def set_initial_turn
    self.turn = rand(1..self.players.length)
    self.turn_player = self.players.find_nth(self.turn, -1).id
    self.save
  end

  def next_turn
    self.turn += 1
    if self.turn > self.players.length
      self.turn = 1
    end
    self.turn_player = self.players.find_nth(self.turn, -1).id
    self.save
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @current_player = @game.players.where(user_id: current_user.id).first
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:num_players)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_current_player.html.erb
<div class="row">
  <div class="col s12 m7">
    <div class="card">
      <div class="card-content">
        <span class="card-title"><%= player.user.name %></span>
        <hr />

        <% player.cards.each do |card| %>
          <p>Card: <%=card.category %> | <%=card.value %> | <%= card.color %>
          <% if @game.turn_player == player.id && card.category == 'M'%>
            <%= link_to 'Play Card', playmerc_game_player_path(@game, player, card_id: card.id), method: 'POST', class:'right waves-effect waves-light btn' %>
          <% elsif @game.turn_player == player.id && card.category == 'P' %>
          <select class="right">
            <option value="" disabled selected>Choose your option</option>
            <% @game.board.merchants.each do |merchant| %>
              <option><%= link_to "#{merchant.player.user.name}: #{merchant.merchant_card.value}", playpirate_game_player_path(@game, player, card_id: card.id, target_id: merchant.id) %> </option>
            <% end %>
          </select>
          <% end %>
          </p>
          <br /><br />

        <% end %>
      </div>
      <div class="card-action">
        <% player.merchants.each do |merchant| %>
          <p><a>Merchant: <%= merchant.merchant_card.value %></a></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :num_players %><br>
    <%= f.text_field :num_players %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/_player_box.html.erb
<div class="row">
  <div class="col s12 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= player.user.name %></span>
        <% if player.id == @game.turn_player %>
          <span class="right"> It's thier turn </span>
        <% end %>
        <p>Cards: <%= player.cards.count %></p>
      </div>
      <div class="card-action">
        <% player.merchants.each do |merchant| %>
          <p><a>Merchant: <%= merchant.merchant_card.value %></a></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th>Num players</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.num_players %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Num players:</strong>
  <%= @game.num_players %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>
<hr/>
<% if @game.turn_player == current_user.player.id %>
<h3>Its Your turn</h3>
<%= link_to 'Draw Card', draw_game_player_path(@game, current_user.player), method: 'POST', class:'waves-effect waves-light btn' %>
<% end %>
<div class="right">Cards in Deck: <%= @game.deck.deck_cards.length %></div>

<% @game.players.each do |player| %>
  <% if player.user != current_user %>
    <%= render partial: 'player_box', locals: { player: player } %>
  <% end %>
<% end %>

<%= render partial: 'current_player', locals: { player: @current_player } %>